remote_theme: abhinavs/moonwalk
title: AiredDev's Notes
url: https://AiredDev.github.io
description: Notes on courses I've taken and books I've read.

include: _resources

theme_config:
  appearance: "dark"
  appearance_toggle: true
  date_format: "%d/%m/%y"
  show_navbar: true
  show_footer: true
  show_copyright: false
  show_projects: false
  show_blog: true
  show_old_projects: false
  show_misc_list: true
